// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkcY3yQUz77BH7oAilr1hskvZsld6rDw',
    appId: '1:576562179070:web:daf54afb56130de2c82eaf',
    messagingSenderId: '576562179070',
    projectId: 'mark-i-inferno',
    authDomain: 'mark-i-inferno.firebaseapp.com',
    databaseURL: 'https://mark-i-inferno-default-rtdb.firebaseio.com',
    storageBucket: 'mark-i-inferno.appspot.com',
    measurementId: 'G-7QG03LDKCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxm198eJMpZzqs47e497nF6gPDSUPpuRA',
    appId: '1:576562179070:android:a4d976b0e4f7bb0fc82eaf',
    messagingSenderId: '576562179070',
    projectId: 'mark-i-inferno',
    databaseURL: 'https://mark-i-inferno-default-rtdb.firebaseio.com',
    storageBucket: 'mark-i-inferno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuX7zremhOOb4V523JDDkGn5kFyNLv41Y',
    appId: '1:576562179070:ios:a724d801f7eec73dc82eaf',
    messagingSenderId: '576562179070',
    projectId: 'mark-i-inferno',
    databaseURL: 'https://mark-i-inferno-default-rtdb.firebaseio.com',
    storageBucket: 'mark-i-inferno.appspot.com',
    iosBundleId: 'com.example.proyekAplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuX7zremhOOb4V523JDDkGn5kFyNLv41Y',
    appId: '1:576562179070:ios:54a1bbc34bea0f1bc82eaf',
    messagingSenderId: '576562179070',
    projectId: 'mark-i-inferno',
    databaseURL: 'https://mark-i-inferno-default-rtdb.firebaseio.com',
    storageBucket: 'mark-i-inferno.appspot.com',
    iosBundleId: 'com.example.proyekAplikasi.RunnerTests',
  );
}
