// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuutF4Pb112mjrP6Abun0LiW2737SO7jY',
    appId: '1:333978274880:web:46421dde05f3c895da63a5',
    messagingSenderId: '333978274880',
    projectId: 'proyekaplikasi-38dde',
    authDomain: 'proyekaplikasi-38dde.firebaseapp.com',
    storageBucket: 'proyekaplikasi-38dde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGoW7F2btWETlZzWXIQo7sEi1Tiq24Ltg',
    appId: '1:333978274880:android:97a8a9809965ff9cda63a5',
    messagingSenderId: '333978274880',
    projectId: 'proyekaplikasi-38dde',
    storageBucket: 'proyekaplikasi-38dde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKblQz5QSUAmMjWFaTXm0iYY8R6NKjW_Y',
    appId: '1:333978274880:ios:5435317b91e22372da63a5',
    messagingSenderId: '333978274880',
    projectId: 'proyekaplikasi-38dde',
    storageBucket: 'proyekaplikasi-38dde.appspot.com',
    iosBundleId: 'com.example.proyekAplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKblQz5QSUAmMjWFaTXm0iYY8R6NKjW_Y',
    appId: '1:333978274880:ios:1674b0f088813649da63a5',
    messagingSenderId: '333978274880',
    projectId: 'proyekaplikasi-38dde',
    storageBucket: 'proyekaplikasi-38dde.appspot.com',
    iosBundleId: 'com.example.proyekAplikasi.RunnerTests',
  );
}
